version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - my_pgsql_volume:/var/lib/postgresql/data/
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    command: [ "sh", "-c", "chown -R postgres:postgres /docker-entrypoint-initdb.d/ && chmod -R 755 /docker-entrypoint-initdb.d/ && docker-entrypoint.sh postgres" ]
  redis:
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  my_pgsql_volume:
    name: db_volume